version: '3.9'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_DATABASE: cursonodejs
    ports:
      - "4000:3306"
    volumes:
      - C:\Users\Alex\Documents\nodejs\volumes:/var/lib/mysql